name: cargo_bike
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=2.17.1 <3.0.1"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.14
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_osm_plugin: ^0.34.1
  geocoding: ^2.0.4
  http: ^0.13.4
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
