// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWVG_vv9GPrkHCO9-Jda1twpCRPX-Wwo',
    appId: '1:129055605471:web:eff5a171af9dd8f3dddf6a',
    messagingSenderId: '129055605471',
    projectId: 'cargobike-b1240',
    authDomain: 'cargobike-b1240.firebaseapp.com',
    storageBucket: 'cargobike-b1240.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcW7BfqqyrpxJF6N9Gcc5whEg_g6-ipiM',
    appId: '1:129055605471:android:65477cc564516f3ddddf6a',
    messagingSenderId: '129055605471',
    projectId: 'cargobike-b1240',
    storageBucket: 'cargobike-b1240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7FOn2XDC3sOKnAjW6TV6hBh8kPA_jsw',
    appId: '1:129055605471:ios:95bebbdee52aeb2bdddf6a',
    messagingSenderId: '129055605471',
    projectId: 'cargobike-b1240',
    storageBucket: 'cargobike-b1240.appspot.com',
    iosClientId: '129055605471-8bbivu6lva55v00lip6selmj0ird6vb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargoBike',
  );
}
